### ISSUE TITLE
State of the field section missing in paper

### ISSUE THREAD

**Issue by suragnair** [uab-cgds-worthey/rosalution#87]
According to the JOSS review guidelines, the authors should provide a section titled 'State of the field' which describes how this software compares to other commonly-used packages. This section is currently missing from the [paper](https://github.com/openjournals/joss-reviews/issues/5443).

**Comment by SeriousHorncat** [comment]
Some applications have overlapping aspects; however, none address the direct problem area Rosalution aims to tackle.  We are working on updating the paper to mention some of these overlapping tools more explicitly. 

We didn't include an explicit section for "State of the field' since we observed very few of the recent JOSS publications explicitly had this section in the papers.  Would more clearly defining the state of the field in the "Statement of Need" suffice?

**Comment by suragnair** [comment]
Yes, defining the state of the field in the "Statement of Need" would be great!
